### PR TITLE
fix: handle upload response correctly

### LINKED ISSUE #64: edtr image plugin doesn't work
image upload attempt fails on serlo.org/jobs
image does not appear in the content after selecting the image and clicking on upload 
no helpful information in the console

### PR DESCRIPTION
**Pull request by Knorrke**
fixes #64

### CODE REVIEW

File: plugins/image/src/upload.tsx [hunk 1]
```diff
@@ -162,6 +163,7 @@ export interface UploadConfig {
   allowedExtensions: string[]
   paramName?: string
   getAdditionalFields?: Function
+  getStateFromResponse: (response: any) => Partial<ImagePluginState>
```
Comment (inyono) [inline plugins/image/src/upload.tsx]: I'd prefer `unknown` over `any`. I'll fix this before merge.
